### ISSUE TITLE
Keyword and Password needs checking for valid UTF8?

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/maidsafe_nfs#5]
Invalid UTF8 input might generate a standard error or a zero, as input for the account name and/or password.

Standard error atm looks to be 

```
invalid utf-8: invalid byte near index 0
```

So, I wonder there could be many attempts to create that account and/or password, where users input is invalid UTF8.

While the first instance might create an account and then future attempts be knocked back, if the error message ever changed, perhaps that would allow illusion of successful account creation against that invalid UTF8. Other users attempting account access with a different invalid UTF8 input, might be able to access the same default account - albeit contingent on matching the right pin.

So, perhaps need a loop checking these too?..
this from the [ maidsafe_nfs/examples/rest_api.rs]

```
+    println!("\n------------ Enter Keyword ---------------");
+    std::io::stdin().read_line(&mut keyword);
+
+    println!("\n\n------------ Enter Password --------------");
+    std::io::stdin().read_line(&mut password);
```

Example of invalild UTF8 input can be got from 

```
fn main() {
use std::str::Utf8Error;

let invalid_vec = vec![240, 144, 128];
let mut keyword = String::new();
let keyword = String::from_utf8(invalid_vec).err().unwrap();
println!("{}",keyword);
}
```

If the error is formatted via something like {:#?} or {:?} then that appears to gives byte data, which is perhaps then unique and reflects the users interest but then that is not the non-UTF8 input intended by user and perhaps then should not be trusted?.. or maybe using the byte data detail instead might be an option - I guess maybe not good practice to risk it, as error reporting might not be reliable.

**Comment by hitman401** [comment]
Thanks @davidpbrown. Will have a look at the issue and fix it at the earliest. Cheers :)

**Comment by hitman401** [comment]
@davidpbrown we will be taking up this issue, this week. Either me or @ustulation will look into this. Our `rust-3` sprint was on a higher priority and now it is completed. Thus, we will be picking this issue sooner. Thanks

**Comment by ustulation** [comment]
Strings in rust are valid utf-8 unless one goes via `unsafe` code. `read_line` will succeed filling the string only if it's valid utf-8, otherwise it will return an error (See the return type). That return type is ignored here because it is unnecessary for the sake of the example - the example demonstrates crate-specific functionality, ie., rest-api demo, not how to handle all kinds of errors from a UI or a CLI - it's beyond scope and will be a useless bloat. Closing.
