### ISSUE TITLE
Rest Api example halts at Trying to create an account ....

### ISSUE THREAD

**Issue by mwaa** [maidsafe/maidsafe_nfs#51]
Environment Windows 10 x64
Cargo build using mock routing
Cargo run example

After insertion of key word, password and pin nothing else happens. Just see Trying to create an account ...

**Comment by hitman401** [comment]
Run the network locally and try running the example.

Or for a quick one, use the mock routing feature, `cargo run --example rest_api --features use-mock-routing`. If we use the mock-routing feature then you will be able to test it without running the network locally.
